---
name: docker_lint

on:
  workflow_call:
    inputs:
      dockerfile-path:
        description: 'relative path to dockerfile'
        required: true
        type: string

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: ${{ inputs.dockerfile-path }}
