---
name: docker_lint

on:
  workflow_call:
    inputs:
      dockerfile-path:
        description: 'relative path to dockerfile'
        required: true
        type: string
        default: './Dockerfile'

jobs:
  hadolint:
    runs-on: ubuntu-latest
    container: hadolint/hadolint:v2.7.0-alpine
    steps:
      - uses: actions/checkout@v2
      - run: hadolint ${{ inputs.dockerfile-path }}
