---
name: docker_lint

on:
  workflow_call:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    container: hadolint/hadolint:v2.7.0-alpine
    steps:
      - uses: actions/checkout@v2
      - run: hadolint ./Dockerfile
